---
title: "gas_mileage_calcs"
author: "Evie Vermeer"
date: "2/22/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Attach packages:
library(tidyverse)
library(ggplot2)
```


```{r}
#Read in velocity data 

# Different speeds (km/hr to m/s):

# 80 km/hr = 22.22 m/s
# 120 km/hr = 33.33 m/s
# 40 km/hr = 11.11 m/s
# 5 km/hr = 1.39 m/s

V = c(30,22.22,33.33,11.11,1.39)
```



```{r}

# Look at function auto_fuel_eff in console
# enter:  view(auto_fuel_eff)

# Calculate Power required for a heavy truck (31752 kg) to go different velocities(30,22.22,33.33,11.11,1.39)if its square footage is 16m)

a_heavy = auto_fuel_eff( m=31752,V=c(30,22.22,33.33,11.11,1.39),A=16)

a_heavy

```


```{r}

# Calculate power for a light truck (15000 kg) to go different velocities(30,22.22,33.33,11.11,1.39)if its square footage is 16m)

#auto_fuel_eff = function(crolling=.015, m, g=9.8, V, A, p_air=1.2, cdrag=0.3)  {
  #result = crolling * m * g * V + (1/2) * A * p_air * cdrag * (V^3)


a_light = auto_fuel_eff( m=15000,V=c(30,22.22,33.33,11.11,1.39),A=16)

a_light

```



```{r}
#organize data in dataframe auto_power for plotting
auto_power = data.frame(cbind(V,a_heavy, a_light))

#then view your dataframe

auto_power





```

```{r}

#Create a ggplot, with two lines, 

ggplot() + 
  geom_line(data=auto_power, aes(x=V, y = a_heavy, colour = "a_heavy"))+
  
  geom_line (data= auto_power, aes (x=V, y=a_light, colour= "a_light"))+
  
#add legend 
  
  scale_color_manual(values = c("a_heavy" = "red", "a_light" = "orange"),
                    name = "Truck Size ") + 
#add axis and title  
  
  labs(title = "Power Generated by Different Size Trucks", 
      x= "Velocity (m/s)",
      y= "Power Generated (watts)")


```



