---
title: "Computing Crop Yield"
author: "Evie Vermeer"
date: "2/27/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```


```{r}
# source function
source("~/Bren/Q2/ESM 262 Computing for Environmental Science/esm262/R/crop_yield.R", echo=TRUE)
```



```{r}
# generate sample speeds from a distribution
nsample = 10
fertilizer = rnorm(mean=5, sd=.5, n=nsample)

# create dataframe of sample
crop = data.frame(fertilizer=fertilizer)

# check that 
fertilizer = ifelse(fertilizer < 0, return("fertilizer cannot be negative"), fertilizer)

# enter in total precipitation value for function use 
tp = 20 

# add column for yield 
crop$yield = NA 

#define parameters for crop yield function and run loop for ten years.
#add values to yield column

for (yr in 1:10) {
crop$yield [yr] = crop_yield (fertilizer[yr],tp=tp) }

sum(crop$yield)
```

```{r}
#create visualization of results
ggplot(crop, aes(fertilizer, yield))+geom_point()+labs(y="yield", x="fertilizer")

```










